// Package store provides in-memory data stores for read-only reference data.
package store

import (
	"fmt"

	"github.com/kite/internal/domain/models"
)

// InstitutionStore implements out.InstitutionStore using a compiled-in map.
// No database is needed — institution data changes infrequently and is loaded at startup.
type InstitutionStore struct {
	data map[models.Currency][]*models.Institution
	idx  map[models.Currency]map[string]*models.Institution
}

func NewInstitutionStore() *InstitutionStore {
	s := &InstitutionStore{
		data: make(map[models.Currency][]*models.Institution),
		idx:  make(map[models.Currency]map[string]*models.Institution),
	}
	for currency, entries := range institutionData {
		s.data[currency] = entries
		s.idx[currency] = make(map[string]*models.Institution, len(entries))
		for _, e := range entries {
			s.idx[currency][e.BankCode] = e
		}
	}
	return s
}

func (s *InstitutionStore) ListByCurrency(currency models.Currency) ([]*models.Institution, error) {
	list, ok := s.data[currency]
	if !ok {
		return nil, fmt.Errorf("no institutions found for currency %s", currency)
	}
	return list, nil
}

func (s *InstitutionStore) GetByCode(currency models.Currency, bankCode string) (*models.Institution, error) {
	idx, ok := s.idx[currency]
	if !ok {
		return nil, nil
	}
	inst, ok := idx[bankCode]
	if !ok {
		return nil, nil
	}
	return inst, nil
}

// institutionData is the compiled-in registry of NGN and KES institutions.
var institutionData = map[models.Currency][]*models.Institution{
	models.NGN: {
		{Type: "BANK_TRANSFER", BankCode: "110072", Name: "78 FINANCE COMPANY", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "110005", Name: "3LINE CARD MANAGEMENT LIMITED", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "120001", Name: "9 PAYMENT SOLUTIONS BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "050005", Name: "AAA FINANCE AND INVESTMENT COMPANY LIMITED", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090270", Name: "AB MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "070010", Name: "ABBEY MORTGAGE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090260", Name: "ABOVE ONLY MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090197", Name: "ABU MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090545", Name: "ABULESORO MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090202", Name: "ACCELEREX NETWORK LIMITED", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000014", Name: "ACCESS BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100013", Name: "ACCESS MONEY", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100052", Name: "ACCESS YELLO & BETA", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000005", Name: "ACCESS(DIAMOND) BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090134", Name: "ACCION MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000109", Name: "ADA MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090160", Name: "ADDOSSER MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090268", Name: "ADEYEMI COLLEGE STAFF MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090155", Name: "ADVANS LA FAYETTE  MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090292", Name: "AFEKHAFE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100028", Name: "AG MORTGAGE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090371", Name: "AGOSASA MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090561", Name: "AKUCHUKWU MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090133", Name: "AL-BARAKAH MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090259", Name: "ALEKUN MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090297", Name: "ALERT MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090277", Name: "AL-HAYAT MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090131", Name: "ALLWORKERS MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090548", Name: "ALLY MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090169", Name: "ALPHA KAPITAL MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090489", Name: "ALVANA MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090394", Name: "AMAC MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090180", Name: "AMJU UNIQUE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090116", Name: "AMML MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090529", Name: "AMPERSAND MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090476", Name: "ANCHORAGE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090143", Name: "APEKS MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090376", Name: "APPLE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090282", Name: "ARISE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090001", Name: "ASO SAVINGS", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090544", Name: "ASPIRE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090287", Name: "ASSETMATRIX MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090172", Name: "ASTRAPOLARIS MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090451", Name: "ATBU MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090264", Name: "AUCHI MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090478", Name: "AVUENEGBE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090188", Name: "BAINES CREDIT MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090563", Name: "BALERA MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090181", Name: "BALOGUN FULANI MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090326", Name: "BALOGUN GAMBARI MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090425", Name: "BANEX MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000107", Name: "BAOBAB MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090316", Name: "BAYERO UNIVERSITY MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090127", Name: "BC KASH MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090336", Name: "BIPC MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090555", Name: "BISHOPGATE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090117", Name: "BOCTRUST MICROFINANCE BANK LIMITED", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090444", Name: "BOI MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090319", Name: "BONGHE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090395", Name: "BORGU MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090454", Name: "BORSTAL MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090176", Name: "BOSAK MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090148", Name: "BOWEN MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "070015", Name: "BRENT MORTGAGE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090293", Name: "BRETHREN MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090393", Name: "BRIDGEWAY MICROFINANACE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090308", Name: "BRIGHTWAY MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090568", Name: "BROADVIEW MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090406", Name: "BUSINESS SUPPORT MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090415", Name: "CALABAR MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090445", Name: "CAPSTONE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100026", Name: "CARBON", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090360", Name: "CASHCONNECT MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090498", Name: "CATLAND MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090562", Name: "CEDAR MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100005", Name: "CELLULANT", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090154", Name: "CEMCS MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000028", Name: "CENTRAL BANK OF NIGERIA", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100015", Name: "CHAMS MOBILE", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090397", Name: "CHANELLE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090470", Name: "CHANGHAN RTS MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090440", Name: "CHERISH MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090416", Name: "CHIBUEZE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090141", Name: "CHIKUM MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090490", Name: "CHUKWUNENYE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090144", Name: "CIT MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000009", Name: "CITI BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090254", Name: "COALCAMP MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090374", Name: "COASTLINE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090530", Name: "CONFIDENCE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090553", Name: "CONSISTENT TRUST MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090130", Name: "CONSUMER MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "070021", Name: "COOPERATIVE MORTGAGE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090365", Name: "CORESTEP MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "060001", Name: "CORONATION MERCHANT BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "050001", Name: "COUNTY FINANCE LIMITED", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "070006", Name: "COVENANT MFB", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090159", Name: "CREDIT AFRIQUE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090526", Name: "CRESCENT MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090429", Name: "CROSS RIVER MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "110017", Name: "CROWDFORCE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090414", Name: "CRUTECH MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "110014", Name: "CYBERSPACE LIMITED", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090391", Name: "DAVODANI MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090167", Name: "DAYLIGHT MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "070023", Name: "DELTA TRUST MORTGAGE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090294", Name: "EAGLE FLIGHT MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100021", Name: "EARTHOLEUM", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090156", Name: "E-BARCS MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090427", Name: "EBONYI STATE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000010", Name: "ECOBANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100008", Name: "ECOBANK XPRESS ACCOUNT", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100030", Name: "ECOMOBILE", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090310", Name: "EDFIN MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090097", Name: "EKONDO MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090389", Name: "EK-RELIABLE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090273", Name: "EMERALD MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090114", Name: "EMPIRE TRUST MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "050012", Name: "ENCO FINANCE COMPANY LTD", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000019", Name: "ENTERPRISE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090189", Name: "ESAN MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090166", Name: "ESO-E MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100006", Name: "eTRANZACT", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090304", Name: "EVANGEL MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090332", Name: "EVERGREEN MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090541", Name: "EXCELLENT MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090328", Name: "EYOWO", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090551", Name: "FairMoney", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090330", Name: "FAME MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090179", Name: "FAST MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "060002", Name: "FBNQUEST MERCHANT BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100031", Name: "FCMB MOBILE", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090290", Name: "FCT MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090398", Name: "FEDERAL POLYTECHNIC NEKEDE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090318", Name: "FEDERAL UNIVERSITY DUTSE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090482", Name: "FEDETH MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090298", Name: "FEDPOLY NASARAWA MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100001", Name: "FETS", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "050002", Name: "FEWCHORE FINANCE COMPANY LIMITED", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090153", Name: "FFS MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000007", Name: "FIDELITY BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100019", Name: "FIDELITY MOBILE", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090126", Name: "FIDFUND MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090111", Name: "FINATRUST MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090400", Name: "FINCA MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090366", Name: "FIRMUS MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "110004", Name: "FIRST APPLE LIMITED", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000016", Name: "FIRST BANK OF NIGERIA", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000003", Name: "FIRST CITY MONUMENT BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "070014", Name: "FIRST GENERATION MORTGAGE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090479", Name: "FIRST HERITAGE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090285", Name: "FIRST OPTION MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090164", Name: "FIRST ROYAL MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090107", Name: "FIRST TRUST MORTGAGE BANK PLC", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100014", Name: "FIRSTMONIE WALLET", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "110002", Name: "FLUTTERWAVE TECHNOLOGY SOLUTIONS LIMITED", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090521", Name: "FORESIGHT MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "070002", Name: "FORTIS MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100016", Name: "FORTIS MOBILE", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090486", Name: "FORTRESS MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "400001", Name: "FSDH", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090145", Name: "FULLRANGE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090438", Name: "FUTMINNA MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090158", Name: "FUTO MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090591", Name: "GABSYN MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090484", Name: "GARKI MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090168", Name: "GASHUA MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "070009", Name: "GATEWAY MORTGAGE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090475", Name: "GIANT STRIDE MFB", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090411", Name: "GIGINYA MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090186", Name: "GIREI MICROFINANACE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090441", Name: "GIWA MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000027", Name: "GLOBUS BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090278", Name: "GLORY MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090408", Name: "GMB MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090467", Name: "GOOD NEIGHBORS MFB", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090495", Name: "GOODNEWS MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090122", Name: "GOWANS MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090550", Name: "GREEN ENERGY MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090178", Name: "GREENBANK MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090269", Name: "GREENVILLE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "060004", Name: "GREENWICH MERCHANT BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090195", Name: "GROOMING MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100009", Name: "GT MOBILE", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000013", Name: "GTBANK PLC", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090385", Name: "GTI MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090147", Name: "HACKMAN MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "070017", Name: "HAGGAI MORTGAGE BANK LIMITED", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090291", Name: "HALALCREDIT MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090121", Name: "HASAL MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090363", Name: "HEADWAY MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100017", Name: "HEDONMARK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000020", Name: "HERITAGE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090418", Name: "HIGHLAND MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "070024", Name: "HOMEBASE MORTGAGE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "120002", Name: "HOPE PAYMENT SERVICE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090439", Name: "IBETO MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090118", Name: "IBILE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090519", Name: "IBOM FADAMA MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090520", Name: "IC GLOBAL MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090546", Name: "IJEBU-IFE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090324", Name: "IKENNE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090279", Name: "IKIRE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090571", Name: "ILARO POLY MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090370", Name: "ILISAN MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090430", Name: "ILORA MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090350", Name: "ILORIN MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090258", Name: "IMO STATE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090417", Name: "IMOWO MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100024", Name: "IMPERIAL HOMES MORTGAGE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090157", Name: "INFINITY MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "070016", Name: "INFINITY TRUST MORTGAGE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100029", Name: "INNOVECTIVES KESH", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090434", Name: "INSIGHTS MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100027", Name: "INTELLIFIN", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090386", Name: "INTERLAND MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "110003", Name: "INTERSWITCH LIMITED", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090493", Name: "IPERU MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090149", Name: "IRL MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090377", Name: "ISALEOYO MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090428", Name: "ISHIE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090543", Name: "IWOAMA MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090337", Name: "IYE OKIN MICROFINANCE BANK LTD", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090421", Name: "IZON MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000006", Name: "JAIZ BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090352", Name: "JESSEFIELD MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090003", Name: "JUBILEE-LIFE MORTGAGE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090320", Name: "KADPOLY MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090554", Name: "KAYVEE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090549", Name: "KC MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090191", Name: "KCMB MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100036", Name: "KEGOW(CHAMSMOBILE)", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000002", Name: "KEYSTONE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090487", Name: "KINGDOM COLLEGE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090299", Name: "KONTAGORA MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090380", Name: "KREDI MONEY MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090267", Name: "KUDA MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090450", Name: "KWASU MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "070012", Name: "LAGOS BUILDING AND INVESTMENT COMPANY", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090177", Name: "LAPO MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090271", Name: "LAVENDER MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090372", Name: "LEGEND MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090420", Name: "LETSHEGO MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090557", Name: "LIFEGATE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090477", Name: "LIGHT MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090435", Name: "LINKS MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "070007", Name: "LIVINGTRUST MORTGAGE BANK PLC", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000029", Name: "LOTUS BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090265", Name: "LOVONUS MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100035", Name: "M36", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090465", Name: "MAIN TRUST MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090323", Name: "MAINLAND MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090171", Name: "MAINSTREET MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090174", Name: "MALACHY MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090383", Name: "MANNY MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090410", Name: "MARITIME MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090423", Name: "MAUTECH MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090321", Name: "MAYFAIR MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "070019", Name: "MAYFRESH MORTGAGE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090280", Name: "MEGAPRAISE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090432", Name: "MEMPHIS MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090589", Name: "MERCURY MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090275", Name: "MERIDAN MFB", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090136", Name: "MICROCRED MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090113", Name: "MICROVIS MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090192", Name: "MIDLAND MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090281", Name: "MINT-FINEX MFB", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090455", Name: "MKOBO MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100011", Name: "MKUDI", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090362", Name: "MOLUSI MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "120003", Name: "MOMO PAYMENT SERVICE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090462", Name: "MONARCH MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100020", Name: "MONEY BOX", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090129", Name: "MONEY TRUST MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "120005", Name: "Moneymaster PSB", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090405", Name: "MONIEPOINT MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090448", Name: "MOYOFADE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090392", Name: "MOZFIN MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090190", Name: "MUTUAL BENEFITS MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090151", Name: "MUTUAL TRUST MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090152", Name: "NAGARTA MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090128", Name: "NDIORAH MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090329", Name: "NEPTUNE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090205", Name: "NEW DAWN MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090378", Name: "NEW GOLDEN PASTURES MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090108", Name: "NEW PRUDENTIAL BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090459", Name: "NICE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090505", Name: "NIGERIA PRISONS MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090263", Name: "NIGERIAN NAVY MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "999999", Name: "NIP VIRTUAL BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090194", Name: "NIRSAL NATIONAL MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090283", Name: "NNEW WOMEN MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100032", Name: "NOWNOW DIGITAL SYSTEMS LIMITED", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "060003", Name: "NOVA MERCHANT BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "070001", Name: "NPF MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090364", Name: "NUTURE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090399", Name: "NWANNEGADI MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090437", Name: "OAKLAND MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090333", Name: "OCHE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090119", Name: "OHAFIA MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090565", Name: "OKE-ARO OREDEGBE MFB", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090161", Name: "OKPOGA MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090566", Name: "OKUKU MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090272", Name: "OLABISI ONABANJO UNIVERSITY MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090468", Name: "OLOFIN OWENA MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090404", Name: "OLOWOLAGBA MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090471", Name: "OLUCHUKWU MFB", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090460", Name: "OLUYOLE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090295", Name: "OMIYE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100004", Name: "OPAY", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000036", Name: "OPTIMUS BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090492", Name: "ORAUKWU MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090567", Name: "OROKAM MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090396", Name: "OSCOTECH MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090456", Name: "OSPOLY MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090580", Name: "OTECH MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090542", Name: "OTUO MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100002", Name: "PAGA", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000106", Name: "PAGE FINANCIALS", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "070008", Name: "PAGE MFBank", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100033", Name: "PALMPAY", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000030", Name: "PARALLEX BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090390", Name: "PARKWAY MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100003", Name: "PARKWAY-READYCASH", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000526", Name: "PARRALEX", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090317", Name: "PATRICKGOLD MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "110001", Name: "PAYATTITUDE ONLINE", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "110006", Name: "PAYSTACK PAYMENT LIMITED", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090402", Name: "PEACE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090137", Name: "PECANTRUST MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090196", Name: "PENNYWISE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090135", Name: "PERSONAL TRUST MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090165", Name: "PETRA MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090289", Name: "PILLAR MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "070013", Name: "PLATINUM MORTGAGE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000008", Name: "POLARIS BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090296", Name: "POLYUNWANA MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090412", Name: "PREEMINENT MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000031", Name: "PREMIUM TRUST BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090274", Name: "PRESTIGE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090481", Name: "PRISCO MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090499", Name: "PRISTINE DIVITIS MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000023", Name: "Providus", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090303", Name: "PURPLEMONEY MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090261", Name: "QUICKFUND MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000024", Name: "RAND MERCHANT BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "070011", Name: "REFUGE MORTGAGE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090125", Name: "REGENT MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090463", Name: "REHOBOTH MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090173", Name: "RELIANCE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090198", Name: "RENMONEY MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090322", Name: "REPHIDIM MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090132", Name: "RICHWAY MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090433", Name: "RIGO MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090515", Name: "RIMA GROWTH PATHWAY MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090547", Name: "ROCKSHIELD MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090138", Name: "ROYAL EXCHANGE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090175", Name: "RUBIES MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090286", Name: "SAFE HAVEN MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090485", Name: "SAFEGATE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090006", Name: "SAFETRUST", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090140", Name: "SAGAMU MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "050003", Name: "SAGE GREY FINANCE LIMITED", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090513", Name: "SEAP MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090112", Name: "SEED CAPITAL MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090369", Name: "SEEDVEST MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090502", Name: "SHALOM MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090401", Name: "SHERPERD TRUST MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090559", Name: "SHIELD MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090558", Name: "SHONGOM MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000034", Name: "SIGNATURE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090449", Name: "SLS MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "120004", Name: "SMARTCASH PAYMENT SERVICE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090506", Name: "SOLID ALLIANZE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090524", Name: "SOLIDROCK MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090325", Name: "SPARKLE", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090436", Name: "SPECTRUM MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100007", Name: "STANBIC IBTC @Ease WALLET", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000012", Name: "STANBIC IBTC BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000021", Name: "STANDARD CHARTERED BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090162", Name: "STANFORD MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "070022", Name: "STB MORTGAGE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090262", Name: "STELLAS MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000001", Name: "STERLING BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100022", Name: "STERLING MOBILE", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090340", Name: "STOCKCORP MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090305", Name: "SULSPAP MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090302", Name: "SUNBEAM MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000022", Name: "SUNTRUST BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090446", Name: "SUPPORT MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090564", Name: "SUPREME MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100023", Name: "TAGPAY", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000026", Name: "TAJ BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090560", Name: "TANADI MFB (CRUST)", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090426", Name: "TANGERINE MONEY", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090115", Name: "TCF MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "110007", Name: "TEAMAPT LIMITED", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100010", Name: "TEASY MOBILE", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090373", Name: "THINK FINANCE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000025", Name: "TITAN TRUST BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100039", Name: "TITAN-PAYSTACK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090146", Name: "TRIDENT MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090525", Name: "TRIPLEA MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090327", Name: "TRUST MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090123", Name: "TRUSTBANC J6 MICROFINANCE BANK LIMITED", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090005", Name: "TRUSTBOND MORTGAGE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090276", Name: "TRUSTFUND MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090315", Name: "U & C MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090403", Name: "UDA MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090517", Name: "UHURU MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090331", Name: "UNAAB MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090461", Name: "UNIBADAN MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090266", Name: "UNIBEN MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090193", Name: "UNICAL MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090452", Name: "UNILAG MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090341", Name: "UNILORIN MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090464", Name: "UNIMAID MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000018", Name: "UNION BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000004", Name: "UNITED BANK FOR AFRICA", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000011", Name: "UNITY BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090338", Name: "UNIUYO MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090251", Name: "UNIVERSITY OF NIGERIA, NSUKKA MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "110009", Name: "VENTURE GARDEN NIGERIA LIMITED", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090474", Name: "VERDANT MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090110", Name: "VFD MFB", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090150", Name: "VIRTUE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090139", Name: "VISA MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100012", Name: "VT NETWORKS", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000017", Name: "WEMA BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090120", Name: "WETLAND MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090124", Name: "XSLNCE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090466", Name: "YCT MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090142", Name: "YES MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090252", Name: "YOBE MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "000015", Name: "ZENITH BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100034", Name: "ZENITH EASY WALLET", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100018", Name: "ZENITH MOBILE", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "090504", Name: "ZIKORA MICROFINANCE BANK", Currency: models.NGN},
		{Type: "BANK_TRANSFER", BankCode: "100025", Name: "ZINTERNET - KONGAPAY", Currency: models.NGN},
	},
	models.KES: {
		{Type: "BANK_TRANSFER", BankCode: "0001", Name: "Kenya Commercial Bank", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0002", Name: "Standard Chartered Kenya", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0016", Name: "Citi Bank", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0063", Name: "Diamond Trust Bank", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0003", Name: "ABSA Bank Kenya", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0018", Name: "Middle East Bank", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0068", Name: "Equity Bank", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0006", Name: "Bank of Baroda", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0019", Name: "Bank of Africa", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0031", Name: "Stanbic Bank Kenya", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0035", Name: "African Bank Corporation Limited", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0043", Name: "Ecobank Transnational Inc.", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0048", Name: "Caritas Microfinance Bank", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0050", Name: "Paramount Bank", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0051", Name: "Kingdom Bank Limited", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0053", Name: "Guaranty Trust Holding Company PLC", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0070", Name: "Family Bank", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0007", Name: "National Commercial Bank of Africa", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0023", Name: "Consolidated Bank Kenya", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0061", Name: "Housing Finance Company", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0065", Name: "Commercial International Bank Kenya Limited", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0072", Name: "Gulf African Bank", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0074", Name: "First Community Bank", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0075", Name: "Dubai Islamic Bank", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0078", Name: "Kenya Women Microfinance Bank", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0079", Name: "Faulu Bank", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0010", Name: "Prime Bank Limited", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0025", Name: "Credit Bank Limited", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0032", Name: "Unaitas Sacco", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0055", Name: "Guardian Bank Limited", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0057", Name: "Investments & Mortgage Limited", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0066", Name: "Sidian Bank", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0076", Name: "United Bank for Africa", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0011", Name: "Cooperative Bank of Kenya", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0036", Name: "Choice Microfinance Bank Kenya Limited", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0089", Name: "Stima SACCO", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0012", Name: "National Bank of Kenya", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0054", Name: "Victoria Commercial Bank", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0014", Name: "Oriental Commercial Bank Limited", Currency: models.KES},
		{Type: "BANK_TRANSFER", BankCode: "0060", Name: "SBM Bank Kenya", Currency: models.KES},
		{Type: "MOBILE_MONEY", BankCode: "SAFKEN", Name: "SAFARICOM", Currency: models.KES, Logo: "https://opticash-assets.s3.eu-west-2.amazonaws.com/mepesa.jpg"},
		{Type: "MOBILE_MONEY", BankCode: "AIRKEN", Name: "AIRTEL", Currency: models.KES, Logo: "https://opticash-assets.s3.eu-west-2.amazonaws.com/new_airtel.png"},
	},
}
