// @title           Kite API
// @version         1.0
// @description     Multi-currency wallet — deposits, FX conversions, and payouts.
// @contact.name    Kite Support

// @host      localhost:8085
// @BasePath  /

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Enter: Bearer <token>

package main

import (
	"context"
	"fmt"
	"log/slog"
	"net/http"

	"github.com/gin-gonic/gin"
	"go.uber.org/fx"

	_ "github.com/kite/docs" // generated by swag
	"github.com/kite/internal/infrastructure/bootstrap"
	"github.com/kite/internal/infrastructure/di"
	"github.com/kite/internal/infrastructure/jobs"
)

func main() {
	fx.New(
		di.Module,

		// Server lifecycle
		fx.Invoke(registerLifecycle),
	).Run()
}

func registerLifecycle(
	lc fx.Lifecycle,
	r *gin.Engine,
	cfg *bootstrap.Config,
	processor *jobs.PayoutProcessor,
	logger *slog.Logger,
) {
	server := &http.Server{
		Addr:    fmt.Sprintf(":%s", cfg.Port),
		Handler: r,
	}

	processorCtx, cancelProcessor := context.WithCancel(context.Background())

	lc.Append(fx.Hook{
		OnStart: func(ctx context.Context) error {
			logger.Info("starting kite server", "port", cfg.Port, "env", cfg.AppEnv)

			// Start the payout background job.
			go processor.Start(processorCtx)

			// Start the HTTP server.
			go func() {
				if err := server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
					logger.Error("server error", "error", err)
				}
			}()

			return nil
		},
		OnStop: func(ctx context.Context) error {
			cancelProcessor()
			return server.Shutdown(ctx)
		},
	})
}
