// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Kite Support"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Authenticate and receive a JWT",
                "parameters": [
                    {
                        "description": "Credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.tokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apiutil.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/apiutil.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/signup": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.signupRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controllers.tokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apiutil.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "email already registered",
                        "schema": {
                            "$ref": "#/definitions/apiutil.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/conversions/execute": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Atomically debits the source wallet and credits the target wallet. A quote can only be executed once.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversions"
                ],
                "summary": "Execute a previously obtained FX quote",
                "parameters": [
                    {
                        "description": "Quote to execute",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.executeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.conversionResponse"
                        }
                    },
                    "400": {
                        "description": "quote_expired or invalid_quote_id",
                        "schema": {
                            "$ref": "#/definitions/apiutil.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apiutil.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "quote_already_executed",
                        "schema": {
                            "$ref": "#/definitions/apiutil.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "insufficient_funds",
                        "schema": {
                            "$ref": "#/definitions/apiutil.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/conversions/quote": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a locked rate valid for 45 seconds. Pass the quote ID to /conversions/execute to settle.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversions"
                ],
                "summary": "Request an FX conversion quote",
                "parameters": [
                    {
                        "description": "Conversion parameters",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.quoteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.quoteResponse"
                        }
                    },
                    "400": {
                        "description": "invalid currency",
                        "schema": {
                            "$ref": "#/definitions/apiutil.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apiutil.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/deposits": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Idempotent — repeated calls with the same Idempotency-Key return the original deposit (HTTP 200) without moving money twice.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deposits"
                ],
                "summary": "Simulate a deposit into a currency wallet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unique key per deposit attempt (e.g. crypto.randomUUID())",
                        "name": "Idempotency-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Deposit details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.depositRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Duplicate — existing deposit returned",
                        "schema": {
                            "$ref": "#/definitions/controllers.depositResponse"
                        }
                    },
                    "201": {
                        "description": "New deposit created",
                        "schema": {
                            "$ref": "#/definitions/controllers.depositResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apiutil.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apiutil.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "invalid currency",
                        "schema": {
                            "$ref": "#/definitions/apiutil.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/institutions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all banks and mobile money providers available for payouts in the given currency",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "institutions"
                ],
                "summary": "List institutions for a currency",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Currency code (NGN, KES)",
                        "name": "currency",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.institutionResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apiutil.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/payouts": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Holds funds immediately. Settlement is async (poll GET /payouts/:id). NGN payouts over ₦500,000 are placed in compliance review (202).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payouts"
                ],
                "summary": "Initiate a payout to a bank account",
                "parameters": [
                    {
                        "description": "Payout details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.payoutRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Payout accepted",
                        "schema": {
                            "$ref": "#/definitions/controllers.payoutResponse"
                        }
                    },
                    "202": {
                        "description": "Compliance review — payout held",
                        "schema": {
                            "$ref": "#/definitions/controllers.payoutResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apiutil.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apiutil.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "insufficient_funds",
                        "schema": {
                            "$ref": "#/definitions/apiutil.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/payouts/inquiry": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Performs a name enquiry: given an account number and bank code, returns the registered account holder name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payouts"
                ],
                "summary": "Resolve recipient account name",
                "parameters": [
                    {
                        "description": "Inquiry request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.inquiryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.inquiryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apiutil.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/payouts/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Poll this endpoint after initiating a payout. Status transitions: pending → processing → successful | failed | review.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payouts"
                ],
                "summary": "Get payout status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Payout UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.payoutResponse"
                        }
                    },
                    "400": {
                        "description": "invalid UUID",
                        "schema": {
                            "$ref": "#/definitions/apiutil.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apiutil.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "payout not found",
                        "schema": {
                            "$ref": "#/definitions/apiutil.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/wallets/balances": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallet"
                ],
                "summary": "List wallet balances for all currencies",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.balancesResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apiutil.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/wallets/transactions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallet"
                ],
                "summary": "Paginated transaction history",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default 20, max 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.transactionsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apiutil.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "apiutil.ErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "apiutil.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/apiutil.ErrorBody"
                }
            }
        },
        "controllers.balanceItem": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "currency": {
                    "type": "string"
                },
                "display": {
                    "description": "human-readable e.g. \"100.00\"",
                    "type": "string"
                }
            }
        },
        "controllers.balancesResponse": {
            "type": "object",
            "properties": {
                "balances": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.balanceItem"
                    }
                }
            }
        },
        "controllers.conversionResponse": {
            "type": "object",
            "properties": {
                "amount_in": {
                    "type": "integer"
                },
                "amount_out": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "fee": {
                    "type": "integer"
                },
                "from_currency": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "quoted_rate": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "to_currency": {
                    "type": "string"
                }
            }
        },
        "controllers.depositRequest": {
            "type": "object",
            "required": [
                "amount",
                "currency"
            ],
            "properties": {
                "amount": {
                    "type": "integer",
                    "minimum": 1
                },
                "currency": {
                    "type": "string"
                }
            }
        },
        "controllers.depositResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "idempotency_key": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "controllers.executeRequest": {
            "type": "object",
            "required": [
                "quote_id"
            ],
            "properties": {
                "quote_id": {
                    "type": "string"
                }
            }
        },
        "controllers.inquiryRequest": {
            "type": "object",
            "required": [
                "account_number",
                "bank_code",
                "currency"
            ],
            "properties": {
                "account_number": {
                    "type": "string"
                },
                "bank_code": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                }
            }
        },
        "controllers.inquiryResponse": {
            "type": "object",
            "properties": {
                "account_name": {
                    "type": "string"
                },
                "account_number": {
                    "type": "string"
                },
                "bank_code": {
                    "type": "string"
                },
                "bank_name": {
                    "type": "string"
                },
                "institution_type": {
                    "type": "string"
                }
            }
        },
        "controllers.institutionResponse": {
            "type": "object",
            "properties": {
                "bank_code": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "logo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "controllers.loginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "controllers.payoutRequest": {
            "type": "object",
            "required": [
                "amount",
                "recipient_account_name",
                "recipient_account_number",
                "recipient_bank_code",
                "source_currency"
            ],
            "properties": {
                "amount": {
                    "type": "integer",
                    "minimum": 1
                },
                "recipient_account_name": {
                    "type": "string"
                },
                "recipient_account_number": {
                    "type": "string"
                },
                "recipient_bank_code": {
                    "type": "string"
                },
                "source_currency": {
                    "type": "string"
                }
            }
        },
        "controllers.payoutResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "compliance_flagged": {
                    "type": "boolean"
                },
                "created_at": {
                    "type": "string"
                },
                "failure_reason": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "recipient_account_name": {
                    "type": "string"
                },
                "recipient_account_number": {
                    "type": "string"
                },
                "recipient_bank_code": {
                    "type": "string"
                },
                "reversed_at": {
                    "type": "string"
                },
                "source_currency": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "controllers.quoteRequest": {
            "type": "object",
            "required": [
                "amount_in",
                "from_currency",
                "to_currency"
            ],
            "properties": {
                "amount_in": {
                    "type": "integer",
                    "minimum": 1
                },
                "from_currency": {
                    "type": "string"
                },
                "to_currency": {
                    "type": "string"
                }
            }
        },
        "controllers.quoteResponse": {
            "type": "object",
            "properties": {
                "amount_in": {
                    "type": "integer"
                },
                "amount_out": {
                    "type": "integer"
                },
                "expires_at": {
                    "type": "string"
                },
                "fee": {
                    "type": "integer"
                },
                "from_currency": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "market_rate": {
                    "type": "string"
                },
                "quoted_rate": {
                    "type": "string"
                },
                "seconds_left": {
                    "type": "integer"
                },
                "to_currency": {
                    "type": "string"
                }
            }
        },
        "controllers.signupRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "controllers.tokenResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "controllers.transactionsResponse": {
            "type": "object",
            "properties": {
                "items": {},
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Enter: Bearer \u003ctoken\u003e",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8085",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Kite API",
	Description:      "Multi-currency wallet — deposits, FX conversions, and payouts.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
